/* automatically generated by rust-bindgen */

pub const __GNUCLIKE_ASM: ::kernel::sys::raw::c_uint = 3;
pub const __GNUCLIKE___TYPEOF: ::kernel::sys::raw::c_uint = 1;
pub const __GNUCLIKE___OFFSETOF: ::kernel::sys::raw::c_uint = 1;
pub const __GNUCLIKE___SECTION: ::kernel::sys::raw::c_uint = 1;
pub const __GNUCLIKE_CTOR_SECTION_HANDLING: ::kernel::sys::raw::c_uint = 1;
pub const __GNUCLIKE_BUILTIN_CONSTANT_P: ::kernel::sys::raw::c_uint = 1;
pub const __GNUCLIKE_BUILTIN_VARARGS: ::kernel::sys::raw::c_uint = 1;
pub const __GNUCLIKE_BUILTIN_STDARG: ::kernel::sys::raw::c_uint = 1;
pub const __GNUCLIKE_BUILTIN_VAALIST: ::kernel::sys::raw::c_uint = 1;
pub const __GNUC_VA_LIST_COMPATIBILITY: ::kernel::sys::raw::c_uint = 1;
pub const __GNUCLIKE_BUILTIN_NEXT_ARG: ::kernel::sys::raw::c_uint = 1;
pub const __GNUCLIKE_BUILTIN_MEMCPY: ::kernel::sys::raw::c_uint = 1;
pub const __CC_SUPPORTS_INLINE: ::kernel::sys::raw::c_uint = 1;
pub const __CC_SUPPORTS___INLINE: ::kernel::sys::raw::c_uint = 1;
pub const __CC_SUPPORTS___INLINE__: ::kernel::sys::raw::c_uint = 1;
pub const __CC_SUPPORTS___FUNC__: ::kernel::sys::raw::c_uint = 1;
pub const __CC_SUPPORTS_WARNING: ::kernel::sys::raw::c_uint = 1;
pub const __CC_SUPPORTS_VARADIC_XXX: ::kernel::sys::raw::c_uint = 1;
pub const __CC_SUPPORTS_DYNAMIC_ARRAY_INIT: ::kernel::sys::raw::c_uint = 1;
pub const __POSIX_VISIBLE: ::kernel::sys::raw::c_uint = 200809;
pub const __XSI_VISIBLE: ::kernel::sys::raw::c_uint = 700;
pub const __BSD_VISIBLE: ::kernel::sys::raw::c_uint = 1;
pub const __ISO_C_VISIBLE: ::kernel::sys::raw::c_uint = 2011;
pub const __EXT1_VISIBLE: ::kernel::sys::raw::c_uint = 1;
pub const __CHAR_BIT: ::kernel::sys::raw::c_uint = 8;
pub const __SCHAR_MAX: ::kernel::sys::raw::c_uint = 127;
pub const __SCHAR_MIN: ::kernel::sys::raw::c_int = -128;
pub const __UCHAR_MAX: ::kernel::sys::raw::c_uint = 255;
pub const __USHRT_MAX: ::kernel::sys::raw::c_uint = 65535;
pub const __SHRT_MAX: ::kernel::sys::raw::c_uint = 32767;
pub const __SHRT_MIN: ::kernel::sys::raw::c_int = -32768;
pub const __UINT_MAX: ::kernel::sys::raw::c_uint = 4294967295;
pub const __INT_MAX: ::kernel::sys::raw::c_uint = 2147483647;
pub const __INT_MIN: ::kernel::sys::raw::c_int = -2147483648;
pub const __ULONG_MAX: ::kernel::sys::raw::c_int = -1;
pub const __LONG_MAX: ::kernel::sys::raw::c_ulonglong = 9223372036854775807;
pub const __LONG_MIN: ::kernel::sys::raw::c_longlong = -9223372036854775808;
pub const __ULLONG_MAX: ::kernel::sys::raw::c_int = -1;
pub const __LLONG_MAX: ::kernel::sys::raw::c_ulonglong = 9223372036854775807;
pub const __LLONG_MIN: ::kernel::sys::raw::c_longlong = -9223372036854775808;
pub const __SSIZE_MAX: ::kernel::sys::raw::c_ulonglong = 9223372036854775807;
pub const __SIZE_T_MAX: ::kernel::sys::raw::c_int = -1;
pub const __OFF_MAX: ::kernel::sys::raw::c_ulonglong = 9223372036854775807;
pub const __OFF_MIN: ::kernel::sys::raw::c_longlong = -9223372036854775808;
pub const __UQUAD_MAX: ::kernel::sys::raw::c_int = -1;
pub const __QUAD_MAX: ::kernel::sys::raw::c_ulonglong = 9223372036854775807;
pub const __QUAD_MIN: ::kernel::sys::raw::c_longlong = -9223372036854775808;
pub const __LONG_BIT: ::kernel::sys::raw::c_uint = 64;
pub const __WORD_BIT: ::kernel::sys::raw::c_uint = 32;
pub const __MINSIGSTKSZ: ::kernel::sys::raw::c_uint = 2048;
pub const __WCHAR_MIN: ::kernel::sys::raw::c_int = -2147483648;
pub const __WCHAR_MAX: ::kernel::sys::raw::c_uint = 2147483647;
pub const _QUAD_HIGHWORD: ::kernel::sys::raw::c_uint = 1;
pub const _QUAD_LOWWORD: ::kernel::sys::raw::c_uint = 0;
pub const _LITTLE_ENDIAN: ::kernel::sys::raw::c_uint = 1234;
pub const _BIG_ENDIAN: ::kernel::sys::raw::c_uint = 4321;
pub const _PDP_ENDIAN: ::kernel::sys::raw::c_uint = 3412;
pub const _BYTE_ORDER: ::kernel::sys::raw::c_uint = 1234;
pub const LITTLE_ENDIAN: ::kernel::sys::raw::c_uint = 1234;
pub const BIG_ENDIAN: ::kernel::sys::raw::c_uint = 4321;
pub const PDP_ENDIAN: ::kernel::sys::raw::c_uint = 3412;
pub const BYTE_ORDER: ::kernel::sys::raw::c_uint = 1234;
pub const __bool_true_false_are_defined: ::kernel::sys::raw::c_uint = 1;
pub const false_: ::kernel::sys::raw::c_uint = 0;
pub const true_: ::kernel::sys::raw::c_uint = 1;
pub const _SIG_WORDS: ::kernel::sys::raw::c_uint = 4;
pub const _SIG_MAXSIG: ::kernel::sys::raw::c_uint = 128;
pub const FD_SETSIZE: ::kernel::sys::raw::c_uint = 1024;
pub const MDT_DEPEND: ::kernel::sys::raw::c_uint = 1;
pub const MDT_MODULE: ::kernel::sys::raw::c_uint = 2;
pub const MDT_VERSION: ::kernel::sys::raw::c_uint = 3;
pub const MDT_PNP_INFO: ::kernel::sys::raw::c_uint = 4;
pub const MDT_STRUCT_VERSION: ::kernel::sys::raw::c_uint = 1;
pub const MDT_SETNAME: &'static [u8; 16usize] = b"modmetadata_set\x00";
pub const MAXMODNAME: ::kernel::sys::raw::c_uint = 32;
pub type __int8_t = ::kernel::sys::raw::c_schar;
pub type __uint8_t = ::kernel::sys::raw::c_uchar;
pub type __int16_t = ::kernel::sys::raw::c_short;
pub type __uint16_t = ::kernel::sys::raw::c_ushort;
pub type __int32_t = ::kernel::sys::raw::c_int;
pub type __uint32_t = ::kernel::sys::raw::c_uint;
pub type __int64_t = ::kernel::sys::raw::c_long;
pub type __uint64_t = ::kernel::sys::raw::c_ulong;
pub type __clock_t = __int32_t;
pub type __critical_t = __int64_t;
pub type __double_t = f64;
pub type __float_t = f32;
pub type __intfptr_t = __int64_t;
pub type __intptr_t = __int64_t;
pub type __intmax_t = __int64_t;
pub type __int_fast8_t = __int32_t;
pub type __int_fast16_t = __int32_t;
pub type __int_fast32_t = __int32_t;
pub type __int_fast64_t = __int64_t;
pub type __int_least8_t = __int8_t;
pub type __int_least16_t = __int16_t;
pub type __int_least32_t = __int32_t;
pub type __int_least64_t = __int64_t;
pub type __ptrdiff_t = __int64_t;
pub type __register_t = __int64_t;
pub type __segsz_t = __int64_t;
pub type __size_t = __uint64_t;
pub type __ssize_t = __int64_t;
pub type __time_t = __int64_t;
pub type __uintfptr_t = __uint64_t;
pub type __uintptr_t = __uint64_t;
pub type __uintmax_t = __uint64_t;
pub type __uint_fast8_t = __uint32_t;
pub type __uint_fast16_t = __uint32_t;
pub type __uint_fast32_t = __uint32_t;
pub type __uint_fast64_t = __uint64_t;
pub type __uint_least8_t = __uint8_t;
pub type __uint_least16_t = __uint16_t;
pub type __uint_least32_t = __uint32_t;
pub type __uint_least64_t = __uint64_t;
pub type __u_register_t = __uint64_t;
pub type __vm_offset_t = __uint64_t;
pub type __vm_paddr_t = __uint64_t;
pub type __vm_size_t = __uint64_t;
pub type ___wchar_t = ::kernel::sys::raw::c_int;
pub type __blksize_t = __int32_t;
pub type __blkcnt_t = __int64_t;
pub type __clockid_t = __int32_t;
pub type __fflags_t = __uint32_t;
pub type __fsblkcnt_t = __uint64_t;
pub type __fsfilcnt_t = __uint64_t;
pub type __gid_t = __uint32_t;
pub type __id_t = __int64_t;
pub type __ino_t = __uint64_t;
pub type __key_t = ::kernel::sys::raw::c_long;
pub type __lwpid_t = __int32_t;
pub type __mode_t = __uint16_t;
pub type __accmode_t = ::kernel::sys::raw::c_int;
pub type __nl_item = ::kernel::sys::raw::c_int;
pub type __nlink_t = __uint64_t;
pub type __off_t = __int64_t;
pub type __off64_t = __int64_t;
pub type __pid_t = __int32_t;
pub type __rlim_t = __int64_t;
pub type __sa_family_t = __uint8_t;
pub type __socklen_t = __uint32_t;
pub type __suseconds_t = ::kernel::sys::raw::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __timer {
    _unused: [u8; 0],
}
pub type __timer_t = *mut __timer;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __mq {
    _unused: [u8; 0],
}
pub type __mqd_t = *mut __mq;
pub type __uid_t = __uint32_t;
pub type __useconds_t = ::kernel::sys::raw::c_uint;
pub type __cpuwhich_t = ::kernel::sys::raw::c_int;
pub type __cpulevel_t = ::kernel::sys::raw::c_int;
pub type __cpusetid_t = ::kernel::sys::raw::c_int;
pub type __ct_rune_t = ::kernel::sys::raw::c_int;
pub type __rune_t = __ct_rune_t;
pub type __wint_t = __ct_rune_t;
pub type __char16_t = __uint_least16_t;
pub type __char32_t = __uint_least32_t;
#[repr(C)]
#[derive(Debug, Default, Copy)]
pub struct __max_align_t {
    pub __max_align1: ::kernel::sys::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __max_align2: f64,
}
#[test]
fn bindgen_test_layout___max_align_t() {
    assert_eq!(::core::mem::size_of::<__max_align_t>() , 32usize , concat ! (
               "Size of: " , stringify ! ( __max_align_t ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const __max_align_t ) ) . __max_align1 as *
                const _ as usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( __max_align_t ) , "::"
                , stringify ! ( __max_align1 ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const __max_align_t ) ) . __max_align2 as *
                const _ as usize } , 16usize , concat ! (
                "Alignment of field: " , stringify ! ( __max_align_t ) , "::"
                , stringify ! ( __max_align2 ) ));
}
impl Clone for __max_align_t {
    fn clone(&self) -> Self { *self }
}
pub type __dev_t = __uint64_t;
pub type __fixpt_t = __uint32_t;
#[repr(C)]
#[derive(Copy)]
pub union __mbstate_t {
    pub __mbstate8: [::kernel::sys::raw::c_char; 128usize],
    pub _mbstateL: __int64_t,
    _bindgen_union_align: [u64; 16usize],
}
#[test]
fn bindgen_test_layout___mbstate_t() {
    assert_eq!(::core::mem::size_of::<__mbstate_t>() , 128usize , concat ! (
               "Size of: " , stringify ! ( __mbstate_t ) ));
    assert_eq! (::core::mem::align_of::<__mbstate_t>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( __mbstate_t ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const __mbstate_t ) ) . __mbstate8 as * const _
                as usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( __mbstate_t ) , "::" ,
                stringify ! ( __mbstate8 ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const __mbstate_t ) ) . _mbstateL as * const _
                as usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( __mbstate_t ) , "::" ,
                stringify ! ( _mbstateL ) ));
}
impl Clone for __mbstate_t {
    fn clone(&self) -> Self { *self }
}
impl Default for __mbstate_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
impl ::kernel::fmt::Debug for __mbstate_t {
    fn fmt(&self, f: &mut ::kernel::fmt::Formatter) -> ::kernel::fmt::Result {
        write!(f , "__mbstate_t {{ union }}")
    }
}
pub type __rman_res_t = __uintmax_t;
pub type __va_list = __builtin_va_list;
pub type __gnuc_va_list = __va_list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_attr {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_cond {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_cond_attr {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_mutex {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_mutex_attr {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct pthread_once {
    pub state: ::kernel::sys::raw::c_int,
    pub mutex: pthread_mutex_t,
}
#[test]
fn bindgen_test_layout_pthread_once() {
    assert_eq!(::core::mem::size_of::<pthread_once>() , 16usize , concat ! (
               "Size of: " , stringify ! ( pthread_once ) ));
    assert_eq! (::core::mem::align_of::<pthread_once>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( pthread_once ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const pthread_once ) ) . state as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( pthread_once ) , "::" ,
                stringify ! ( state ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const pthread_once ) ) . mutex as * const _ as
                usize } , 8usize , concat ! (
                "Alignment of field: " , stringify ! ( pthread_once ) , "::" ,
                stringify ! ( mutex ) ));
}
impl Clone for pthread_once {
    fn clone(&self) -> Self { *self }
}
impl Default for pthread_once {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_rwlock {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_rwlockattr {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_barrier {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_barrier_attr {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_spinlock {
    _unused: [u8; 0],
}
pub type pthread_t = *mut pthread;
pub type pthread_attr_t = *mut pthread_attr;
pub type pthread_mutex_t = *mut pthread_mutex;
pub type pthread_mutexattr_t = *mut pthread_mutex_attr;
pub type pthread_cond_t = *mut pthread_cond;
pub type pthread_condattr_t = *mut pthread_cond_attr;
pub type pthread_key_t = ::kernel::sys::raw::c_int;
pub type pthread_once_t = pthread_once;
pub type pthread_rwlock_t = *mut pthread_rwlock;
pub type pthread_rwlockattr_t = *mut pthread_rwlockattr;
pub type pthread_barrier_t = *mut pthread_barrier;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_barrierattr {
    _unused: [u8; 0],
}
pub type pthread_barrierattr_t = *mut pthread_barrierattr;
pub type pthread_spinlock_t = *mut pthread_spinlock;
pub type pthread_addr_t = *mut ::kernel::sys::raw::c_void;
pub type pthread_startroutine_t =
    ::core::option::Option<unsafe extern "C" fn(arg1:
                                                    *mut ::kernel::sys::raw::c_void)
                               -> *mut ::kernel::sys::raw::c_void>;
pub type u_char = ::kernel::sys::raw::c_uchar;
pub type u_short = ::kernel::sys::raw::c_ushort;
pub type u_int = ::kernel::sys::raw::c_uint;
pub type u_long = ::kernel::sys::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type u_int8_t = __uint8_t;
pub type u_int16_t = __uint16_t;
pub type u_int32_t = __uint32_t;
pub type u_int64_t = __uint64_t;
pub type u_quad_t = __uint64_t;
pub type quad_t = __int64_t;
pub type qaddr_t = *mut quad_t;
pub type caddr_t = *mut ::kernel::sys::raw::c_char;
pub type c_caddr_t = *const ::kernel::sys::raw::c_char;
pub type blksize_t = __blksize_t;
pub type cpuwhich_t = __cpuwhich_t;
pub type cpulevel_t = __cpulevel_t;
pub type cpusetid_t = __cpusetid_t;
pub type blkcnt_t = __blkcnt_t;
pub type clock_t = __clock_t;
pub type clockid_t = __clockid_t;
pub type critical_t = __critical_t;
pub type daddr_t = __int64_t;
pub type dev_t = __dev_t;
pub type fflags_t = __fflags_t;
pub type fixpt_t = __fixpt_t;
pub type fsblkcnt_t = __fsblkcnt_t;
pub type fsfilcnt_t = __fsfilcnt_t;
pub type gid_t = __gid_t;
pub type in_addr_t = __uint32_t;
pub type in_port_t = __uint16_t;
pub type id_t = __id_t;
pub type ino_t = __ino_t;
pub type key_t = __key_t;
pub type lwpid_t = __lwpid_t;
pub type mode_t = __mode_t;
pub type accmode_t = __accmode_t;
pub type nlink_t = __nlink_t;
pub type off_t = __off_t;
pub type off64_t = __off64_t;
pub type pid_t = __pid_t;
pub type register_t = __register_t;
pub type rlim_t = __rlim_t;
pub type sbintime_t = __int64_t;
pub type segsz_t = __segsz_t;
pub type suseconds_t = __suseconds_t;
pub type time_t = __time_t;
pub type timer_t = __timer_t;
pub type mqd_t = __mqd_t;
pub type u_register_t = __u_register_t;
pub type uid_t = __uid_t;
pub type useconds_t = __useconds_t;
pub type cap_ioctl_t = ::kernel::sys::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cap_rights {
    _unused: [u8; 0],
}
pub type cap_rights_t = cap_rights;
pub type kvaddr_t = __uint64_t;
pub type ksize_t = __uint64_t;
pub type vm_offset_t = __vm_offset_t;
pub type vm_ooffset_t = __int64_t;
pub type vm_paddr_t = __vm_paddr_t;
pub type vm_pindex_t = __uint64_t;
pub type vm_size_t = __vm_size_t;
pub type rman_res_t = __rman_res_t;
pub type boolean_t = ::kernel::sys::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct device {
    _unused: [u8; 0],
}
pub type device_t = *mut device;
pub type intfptr_t = __intfptr_t;
pub type intrmask_t = __uint32_t;
pub type uintfptr_t = __uintfptr_t;
pub type uoff_t = __uint64_t;
pub type vm_memattr_t = ::kernel::sys::raw::c_char;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vm_page {
    _unused: [u8; 0],
}
pub type vm_page_t = *mut vm_page;
pub type bool_ = bool;
#[repr(C)]
#[derive(Debug, Default, Copy)]
pub struct __sigset {
    pub __bits: [__uint32_t; 4usize],
}
#[test]
fn bindgen_test_layout___sigset() {
    assert_eq!(::core::mem::size_of::<__sigset>() , 16usize , concat ! (
               "Size of: " , stringify ! ( __sigset ) ));
    assert_eq! (::core::mem::align_of::<__sigset>() , 4usize , concat ! (
                "Alignment of " , stringify ! ( __sigset ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const __sigset ) ) . __bits as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( __sigset ) , "::" ,
                stringify ! ( __bits ) ));
}
impl Clone for __sigset {
    fn clone(&self) -> Self { *self }
}
pub type __sigset_t = __sigset;
#[repr(C)]
#[derive(Debug, Default, Copy)]
pub struct timeval {
    pub tv_sec: time_t,
    pub tv_usec: suseconds_t,
}
#[test]
fn bindgen_test_layout_timeval() {
    assert_eq!(::core::mem::size_of::<timeval>() , 16usize , concat ! (
               "Size of: " , stringify ! ( timeval ) ));
    assert_eq! (::core::mem::align_of::<timeval>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( timeval ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const timeval ) ) . tv_sec as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( timeval ) , "::" ,
                stringify ! ( tv_sec ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const timeval ) ) . tv_usec as * const _ as
                usize } , 8usize , concat ! (
                "Alignment of field: " , stringify ! ( timeval ) , "::" ,
                stringify ! ( tv_usec ) ));
}
impl Clone for timeval {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
#[derive(Debug, Default, Copy)]
pub struct timespec {
    pub tv_sec: time_t,
    pub tv_nsec: ::kernel::sys::raw::c_long,
}
#[test]
fn bindgen_test_layout_timespec() {
    assert_eq!(::core::mem::size_of::<timespec>() , 16usize , concat ! (
               "Size of: " , stringify ! ( timespec ) ));
    assert_eq! (::core::mem::align_of::<timespec>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( timespec ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const timespec ) ) . tv_sec as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( timespec ) , "::" ,
                stringify ! ( tv_sec ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const timespec ) ) . tv_nsec as * const _ as
                usize } , 8usize , concat ! (
                "Alignment of field: " , stringify ! ( timespec ) , "::" ,
                stringify ! ( tv_nsec ) ));
}
impl Clone for timespec {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
#[derive(Debug, Default, Copy)]
pub struct itimerspec {
    pub it_interval: timespec,
    pub it_value: timespec,
}
#[test]
fn bindgen_test_layout_itimerspec() {
    assert_eq!(::core::mem::size_of::<itimerspec>() , 32usize , concat ! (
               "Size of: " , stringify ! ( itimerspec ) ));
    assert_eq! (::core::mem::align_of::<itimerspec>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( itimerspec ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const itimerspec ) ) . it_interval as * const _
                as usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( itimerspec ) , "::" ,
                stringify ! ( it_interval ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const itimerspec ) ) . it_value as * const _ as
                usize } , 16usize , concat ! (
                "Alignment of field: " , stringify ! ( itimerspec ) , "::" ,
                stringify ! ( it_value ) ));
}
impl Clone for itimerspec {
    fn clone(&self) -> Self { *self }
}
pub type __fd_mask = ::kernel::sys::raw::c_ulong;
pub type fd_mask = __fd_mask;
pub type sigset_t = __sigset_t;
#[repr(C)]
#[derive(Debug, Default, Copy)]
pub struct fd_set {
    pub __fds_bits: [__fd_mask; 16usize],
}
#[test]
fn bindgen_test_layout_fd_set() {
    assert_eq!(::core::mem::size_of::<fd_set>() , 128usize , concat ! (
               "Size of: " , stringify ! ( fd_set ) ));
    assert_eq! (::core::mem::align_of::<fd_set>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( fd_set ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const fd_set ) ) . __fds_bits as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( fd_set ) , "::" ,
                stringify ! ( __fds_bits ) ));
}
impl Clone for fd_set {
    fn clone(&self) -> Self { *self }
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum modeventtype {
    MOD_LOAD = 0,
    MOD_UNLOAD = 1,
    MOD_SHUTDOWN = 2,
    MOD_QUIESCE = 3,
}
pub use self::modeventtype as modeventtype_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct module {
    _unused: [u8; 0],
}
pub type module_t = *mut module;
pub type modeventhand_t =
    ::core::option::Option<unsafe extern "C" fn(arg1: module_t,
                                                arg2:
                                                    ::kernel::sys::raw::c_int,
                                                arg3:
                                                    *mut ::kernel::sys::raw::c_void)
                               -> ::kernel::sys::raw::c_int>;
#[repr(C)]
#[derive(Debug, Copy)]
pub struct moduledata {
    pub name: *const ::kernel::sys::raw::c_char,
    pub evhand: modeventhand_t,
    pub priv_: *mut ::kernel::sys::raw::c_void,
}
#[test]
fn bindgen_test_layout_moduledata() {
    assert_eq!(::core::mem::size_of::<moduledata>() , 24usize , concat ! (
               "Size of: " , stringify ! ( moduledata ) ));
    assert_eq! (::core::mem::align_of::<moduledata>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( moduledata ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const moduledata ) ) . name as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( moduledata ) , "::" ,
                stringify ! ( name ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const moduledata ) ) . evhand as * const _ as
                usize } , 8usize , concat ! (
                "Alignment of field: " , stringify ! ( moduledata ) , "::" ,
                stringify ! ( evhand ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const moduledata ) ) . priv_ as * const _ as
                usize } , 16usize , concat ! (
                "Alignment of field: " , stringify ! ( moduledata ) , "::" ,
                stringify ! ( priv_ ) ));
}
impl Clone for moduledata {
    fn clone(&self) -> Self { *self }
}
impl Default for moduledata {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type moduledata_t = moduledata;
#[repr(C)]
#[derive(Copy)]
pub union modspecific {
    pub intval: ::kernel::sys::raw::c_int,
    pub uintval: u_int,
    pub longval: ::kernel::sys::raw::c_long,
    pub ulongval: u_long,
    _bindgen_union_align: u64,
}
#[test]
fn bindgen_test_layout_modspecific() {
    assert_eq!(::core::mem::size_of::<modspecific>() , 8usize , concat ! (
               "Size of: " , stringify ! ( modspecific ) ));
    assert_eq! (::core::mem::align_of::<modspecific>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( modspecific ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const modspecific ) ) . intval as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( modspecific ) , "::" ,
                stringify ! ( intval ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const modspecific ) ) . uintval as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( modspecific ) , "::" ,
                stringify ! ( uintval ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const modspecific ) ) . longval as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( modspecific ) , "::" ,
                stringify ! ( longval ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const modspecific ) ) . ulongval as * const _
                as usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( modspecific ) , "::" ,
                stringify ! ( ulongval ) ));
}
impl Clone for modspecific {
    fn clone(&self) -> Self { *self }
}
impl Default for modspecific {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
impl ::kernel::fmt::Debug for modspecific {
    fn fmt(&self, f: &mut ::kernel::fmt::Formatter) -> ::kernel::fmt::Result {
        write!(f , "modspecific {{ union }}")
    }
}
pub type modspecific_t = modspecific;
#[repr(C)]
#[derive(Debug, Default, Copy)]
pub struct mod_depend {
    pub md_ver_minimum: ::kernel::sys::raw::c_int,
    pub md_ver_preferred: ::kernel::sys::raw::c_int,
    pub md_ver_maximum: ::kernel::sys::raw::c_int,
}
#[test]
fn bindgen_test_layout_mod_depend() {
    assert_eq!(::core::mem::size_of::<mod_depend>() , 12usize , concat ! (
               "Size of: " , stringify ! ( mod_depend ) ));
    assert_eq! (::core::mem::align_of::<mod_depend>() , 4usize , concat ! (
                "Alignment of " , stringify ! ( mod_depend ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_depend ) ) . md_ver_minimum as *
                const _ as usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_depend ) , "::" ,
                stringify ! ( md_ver_minimum ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_depend ) ) . md_ver_preferred as *
                const _ as usize } , 4usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_depend ) , "::" ,
                stringify ! ( md_ver_preferred ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_depend ) ) . md_ver_maximum as *
                const _ as usize } , 8usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_depend ) , "::" ,
                stringify ! ( md_ver_maximum ) ));
}
impl Clone for mod_depend {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
#[derive(Debug, Default, Copy)]
pub struct mod_version {
    pub mv_version: ::kernel::sys::raw::c_int,
}
#[test]
fn bindgen_test_layout_mod_version() {
    assert_eq!(::core::mem::size_of::<mod_version>() , 4usize , concat ! (
               "Size of: " , stringify ! ( mod_version ) ));
    assert_eq! (::core::mem::align_of::<mod_version>() , 4usize , concat ! (
                "Alignment of " , stringify ! ( mod_version ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_version ) ) . mv_version as * const _
                as usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_version ) , "::" ,
                stringify ! ( mv_version ) ));
}
impl Clone for mod_version {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct mod_metadata {
    pub md_version: ::kernel::sys::raw::c_int,
    pub md_type: ::kernel::sys::raw::c_int,
    pub md_data: *const ::kernel::sys::raw::c_void,
    pub md_cval: *const ::kernel::sys::raw::c_char,
}
#[test]
fn bindgen_test_layout_mod_metadata() {
    assert_eq!(::core::mem::size_of::<mod_metadata>() , 24usize , concat ! (
               "Size of: " , stringify ! ( mod_metadata ) ));
    assert_eq! (::core::mem::align_of::<mod_metadata>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( mod_metadata ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_metadata ) ) . md_version as * const
                _ as usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_metadata ) , "::" ,
                stringify ! ( md_version ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_metadata ) ) . md_type as * const _
                as usize } , 4usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_metadata ) , "::" ,
                stringify ! ( md_type ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_metadata ) ) . md_data as * const _
                as usize } , 8usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_metadata ) , "::" ,
                stringify ! ( md_data ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_metadata ) ) . md_cval as * const _
                as usize } , 16usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_metadata ) , "::" ,
                stringify ! ( md_cval ) ));
}
impl Clone for mod_metadata {
    fn clone(&self) -> Self { *self }
}
impl Default for mod_metadata {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct mod_pnp_match_info {
    pub descr: *const ::kernel::sys::raw::c_char,
    pub bus: *const ::kernel::sys::raw::c_char,
    pub table: *const ::kernel::sys::raw::c_void,
    pub entry_len: ::kernel::sys::raw::c_int,
    pub num_entry: ::kernel::sys::raw::c_int,
}
#[test]
fn bindgen_test_layout_mod_pnp_match_info() {
    assert_eq!(::core::mem::size_of::<mod_pnp_match_info>() , 32usize , concat
               ! ( "Size of: " , stringify ! ( mod_pnp_match_info ) ));
    assert_eq! (::core::mem::align_of::<mod_pnp_match_info>() , 8usize ,
                concat ! (
                "Alignment of " , stringify ! ( mod_pnp_match_info ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_pnp_match_info ) ) . descr as * const
                _ as usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_pnp_match_info ) ,
                "::" , stringify ! ( descr ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_pnp_match_info ) ) . bus as * const _
                as usize } , 8usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_pnp_match_info ) ,
                "::" , stringify ! ( bus ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_pnp_match_info ) ) . table as * const
                _ as usize } , 16usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_pnp_match_info ) ,
                "::" , stringify ! ( table ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_pnp_match_info ) ) . entry_len as *
                const _ as usize } , 24usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_pnp_match_info ) ,
                "::" , stringify ! ( entry_len ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const mod_pnp_match_info ) ) . num_entry as *
                const _ as usize } , 28usize , concat ! (
                "Alignment of field: " , stringify ! ( mod_pnp_match_info ) ,
                "::" , stringify ! ( num_entry ) ));
}
impl Clone for mod_pnp_match_info {
    fn clone(&self) -> Self { *self }
}
impl Default for mod_pnp_match_info {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sx {
    _unused: [u8; 0],
}
extern "C" {
    #[link_name = "modules_sx"]
    pub static mut modules_sx: sx;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct linker_file {
    _unused: [u8; 0],
}
extern "C" {
    pub fn module_register_init(arg1: *const ::kernel::sys::raw::c_void);
}
extern "C" {
    pub fn module_register(arg1: *const moduledata, arg2: *mut linker_file)
     -> ::kernel::sys::raw::c_int;
}
extern "C" {
    pub fn module_lookupbyname(arg1: *const ::kernel::sys::raw::c_char)
     -> module_t;
}
extern "C" {
    pub fn module_lookupbyid(arg1: ::kernel::sys::raw::c_int) -> module_t;
}
extern "C" {
    pub fn module_quiesce(arg1: module_t) -> ::kernel::sys::raw::c_int;
}
extern "C" {
    pub fn module_reference(arg1: module_t);
}
extern "C" {
    pub fn module_release(arg1: module_t);
}
extern "C" {
    pub fn module_unload(arg1: module_t) -> ::kernel::sys::raw::c_int;
}
extern "C" {
    pub fn module_getid(arg1: module_t) -> ::kernel::sys::raw::c_int;
}
extern "C" {
    pub fn module_getfnext(arg1: module_t) -> module_t;
}
extern "C" {
    pub fn module_getname(arg1: module_t)
     -> *const ::kernel::sys::raw::c_char;
}
extern "C" {
    pub fn module_setspecific(arg1: module_t, arg2: *mut modspecific_t);
}
extern "C" {
    pub fn module_file(arg1: module_t) -> *mut linker_file;
}
#[repr(C)]
#[derive(Copy)]
pub struct module_stat {
    pub version: ::kernel::sys::raw::c_int,
    pub name: [::kernel::sys::raw::c_char; 32usize],
    pub refs: ::kernel::sys::raw::c_int,
    pub id: ::kernel::sys::raw::c_int,
    pub data: modspecific_t,
}
#[test]
fn bindgen_test_layout_module_stat() {
    assert_eq!(::core::mem::size_of::<module_stat>() , 56usize , concat ! (
               "Size of: " , stringify ! ( module_stat ) ));
    assert_eq! (::core::mem::align_of::<module_stat>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( module_stat ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const module_stat ) ) . version as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( module_stat ) , "::" ,
                stringify ! ( version ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const module_stat ) ) . name as * const _ as
                usize } , 4usize , concat ! (
                "Alignment of field: " , stringify ! ( module_stat ) , "::" ,
                stringify ! ( name ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const module_stat ) ) . refs as * const _ as
                usize } , 36usize , concat ! (
                "Alignment of field: " , stringify ! ( module_stat ) , "::" ,
                stringify ! ( refs ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const module_stat ) ) . id as * const _ as
                usize } , 40usize , concat ! (
                "Alignment of field: " , stringify ! ( module_stat ) , "::" ,
                stringify ! ( id ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const module_stat ) ) . data as * const _ as
                usize } , 48usize , concat ! (
                "Alignment of field: " , stringify ! ( module_stat ) , "::" ,
                stringify ! ( data ) ));
}
impl Clone for module_stat {
    fn clone(&self) -> Self { *self }
}
impl Default for module_stat {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
impl ::kernel::fmt::Debug for module_stat {
    fn fmt(&self, f: &mut ::kernel::fmt::Formatter) -> ::kernel::fmt::Result {
        write!(f ,
               "module_stat {{ version: {:?}, name: [{}], refs: {:?}, id: {:?}, data: {:?} }}"
               , self . version , self . name . iter (  ) . enumerate (  ) .
               map (
               | ( i , v ) | format ! (
               "{}{:?}" , if i > 0 { ", " } else { "" } , v ) ) . collect :: <
               String > (  ) , self . refs , self . id , self . data)
    }
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy)]
pub struct __va_list_tag {
    pub gp_offset: ::kernel::sys::raw::c_uint,
    pub fp_offset: ::kernel::sys::raw::c_uint,
    pub overflow_arg_area: *mut ::kernel::sys::raw::c_void,
    pub reg_save_area: *mut ::kernel::sys::raw::c_void,
}
#[test]
fn bindgen_test_layout___va_list_tag() {
    assert_eq!(::core::mem::size_of::<__va_list_tag>() , 24usize , concat ! (
               "Size of: " , stringify ! ( __va_list_tag ) ));
    assert_eq! (::core::mem::align_of::<__va_list_tag>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( __va_list_tag ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const __va_list_tag ) ) . gp_offset as * const
                _ as usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( __va_list_tag ) , "::"
                , stringify ! ( gp_offset ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const __va_list_tag ) ) . fp_offset as * const
                _ as usize } , 4usize , concat ! (
                "Alignment of field: " , stringify ! ( __va_list_tag ) , "::"
                , stringify ! ( fp_offset ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const __va_list_tag ) ) . overflow_arg_area as
                * const _ as usize } , 8usize , concat ! (
                "Alignment of field: " , stringify ! ( __va_list_tag ) , "::"
                , stringify ! ( overflow_arg_area ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const __va_list_tag ) ) . reg_save_area as *
                const _ as usize } , 16usize , concat ! (
                "Alignment of field: " , stringify ! ( __va_list_tag ) , "::"
                , stringify ! ( reg_save_area ) ));
}
impl Clone for __va_list_tag {
    fn clone(&self) -> Self { *self }
}
impl Default for __va_list_tag {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
